name: secp256r1
description: A new Flutter plugin project.
version: 0.1.0-dev.1
repository: https://github.com/AstroxNetwork/p256

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  agent_dart: ^1.0.0-dev.8
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.astrox.secure_p256_plugin
        pluginClass: SecureP256Plugin
      ios:
        pluginClass: P256Plugin
